version: '3.7'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  db:
    image: postgres:11.15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ticketmarket
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data: